### PR TITLE
Add doc on tech stack

### PR DESCRIPTION
**Pull request by HiranmayaGundu**
A document about the tech stack we want to use. Listed the choices for the UI framework. Based on the decision we make we can choose a styling solution as well Cloud / CDN provider

### CODE REVIEW

**Review by aditya-giri — COMMENTED** [review]
I'm okay with whatever we pick, since we don't really have a lot of architectural decisions to make :P

**Comment by HiranmayaGundu** [comment]
@aditya-giri What are you most comfortable with :P Or what do you want to try out

**Comment by aditya-giri** [comment]
Haven't experimented with web dev except for a little Gatsby. So pretty much anything will be good learning 😛 I'm comfy with TS though because I use it at work.

**Review by seshrs — APPROVED** [review]
Great doc! I haven’t used both gatsby and Next.js, and I kind-of want to try using one of them. 

No strong preference in these decisions.

**Comment by HiranmayaGundu** [comment]
@seshrs Okay let's go with Next.js then, that's my preference!

**Pull request merged**
